### ISSUE TITLE
Add support for others options.

### ISSUE THREAD

**Issue by marcinpraczko** [netresearch/deploy-rst#1]
I think it will be very nice to have support for others options which will allow pass this to confluence-cli.

For example. I am adding page to confluence from RST and everything seems be working fine, but I can't add more arguments to parameters:

```
storePage - Create or update a page.
        Required parameters: space and title or id, content or file
        Optional parameters: parent, labels, comment, minor, content2, findReplace, findReplaceRegex
 noConvert, markdown, encoding
```

All of this parameters are important - and for example there is option about parent which I need.

Hope that helps.

**Comment by vergissberlin** [comment]
**Hi marcinpraczko,**

to create a page with it, is a good idea. I have found an example in confluence documentation to solve this. This example shows how you can create a new page, with content, in a specific space. 

```bash
curl -u admin:admin -X POST -H 'Content-Type: application/json' -d'{"type":"page","title":"new page","space":{"key":"TST"},"body":{"storage":{"value":"<p>This is a new page</p>","representation":"storage"}}}' http://localhost:8080/confluence/rest/api/content/
```
André

**Comment by ngolatka** [comment]
Closed due to inactivity.
